local settings = {
  -- every line should be same width without escaped \
  header = {
    type = 'text',
    oldfiles_directory = false,
    align = 'center',
    fold_section = false,
    title = 'Header',
    margin = 5,
    content = {
      [[                                                                       ]],
      [[                                                                     ]],
      [[       ████ ██████           █████      ██                     ]],
      [[      ███████████             █████                             ]],
      [[      █████████ ███████████████████ ███   ███████████   ]],
      [[     █████████  ███    █████████████ █████ ██████████████   ]],
      [[    █████████ ██████████ █████████ █████ █████ ████ █████   ]],
      [[  ███████████ ███    ███ █████████ █████ █████ ████ █████  ]],
      [[ ██████  █████████████████████ ████ █████ █████ ████ ██████ ]],
      [[                                                                       ]],
    },
    highlight = 'Statement',
    default_color = '',
    oldfiles_amount = 0,
  },
  -- name which will be displayed and command
  body = {
    type = 'mapping',
    oldfiles_directory = false,
    align = 'center',
    fold_section = false,
    title = 'Basic Commands',
    margin = 5,
    content = {
      { ' Find File', 		'Telescope find_files', 		'<leader>sf' },
      { '󰍉 Find Word', 		'Telescope live_grep', 			'<leader>sg' },
      { ' Recent Files', 	'Telescope oldfiles', 			'<leader>so' },
      { ' File Browser', 	'Neotree float', 			'\\\\' },
      { ' Colorschemes', 	'Telescope colorscheme', 		'<leader>sc' },
      { ' New File', 		"lua require'startup'.new_file()", 	'<leader>nf' },
    },
    highlight = 'String',
    default_color = '',
    oldfiles_amount = 0,
  },
  body_2 = {
    type = 'oldfiles',
    oldfiles_directory = false,
    align = 'left',
    fold_section = false,
    title = 'Oldfiles',
    margin = 5,
    content = '',
    highlight = 'String',
    default_color = '',
    oldfiles_amount = 5,
  },
  options = {
	   after = function()
		require('startup.utils').oldfiles_mappings()
	   end,
    mapping_keys =true,
    cursor_column = 0.5,
    empty_lines_between_mappings = true,
    disable_statuslines = true,
    paddings = { 1, 3, 3, 0 },
  },
  mappings = {
    execute_command = '<CR>',
    open_file = 'o',
    open_file_split = '<c-o>',
    open_section = '<TAB>',
    open_help = '?',
  },
  colors = {
    background = '#1f2227',
    folded_section = '#56b6c2',
  },
  parts = { 'header', 'body' , 'body_2'  },
}
return settings
